# Generated by Django 3.1.6 on 2021-03-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0005_auto_20200715_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='alamat_email',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='bagi_hasil',
        ),
        migrations.AlterField(
            model_name='coach',
            name='alamat_kotakab',
            field=models.CharField(blank=True, max_length=20, verbose_name='Alamat Kota/ Kab.'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='alamat_tinggal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coach',
            name='nama_bank',
            field=models.CharField(blank=True, help_text='Diutamakan Bank Mandiri', max_length=20),
        ),
        migrations.AlterField(
            model_name='coach',
            name='nomor_ktp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='coach',
            name='nomor_ponsel',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='coach',
            name='nomor_rekening',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
