# Generated by Django 3.1.6 on 2021-03-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_auto_20200715_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='kategori',
        ),
        migrations.AlterField(
            model_name='order',
            name='p1_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='p1_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='p2_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='p2_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='p3_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='p3_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='p4_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='p4_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='p5_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='p5_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='p6_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='p6_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='p7_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='p7_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='p8_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='p8_c',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='nama_produk',
            field=models.CharField(max_length=50),
        ),
    ]
