# Generated by Django 3.1.6 on 2021-03-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_auto_20210319_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fee_pelatih',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
