# Generated by Django 3.1.6 on 2021-03-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_product_fee_pelatih'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='jenis_order',
            field=models.CharField(blank=True, choices=[('p', 'Privat'), ('k', 'Kelas')], default='p', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fee_pelatih',
            field=models.IntegerField(null=True),
        ),
    ]
