# Generated by Django 3.1.6 on 2021-03-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_auto_20210319_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='jenis_order',
            field=models.CharField(choices=[('p', 'Privat'), ('k', 'Kelas')], default='p', max_length=1),
        ),
    ]
