# Generated by Django 3.1.6 on 2021-03-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_newsfeed_waktu_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsfeed',
            options={'ordering': ['-waktu_post']},
        ),
    ]
