# Generated by Django 3.1.6 on 2021-03-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0008_auto_20200713_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='alamat_email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AlterField(
            model_name='student',
            name='alamat_kotakab',
            field=models.CharField(blank=True, max_length=20, verbose_name='Alamat Kota/ Kab.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='alamat_tinggal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='nomor_ponsel',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
